<a href="https://colab.research.google.com/github/musharrafhamraz/Python-Problems/blob/main/Numpy_Lab.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
a = np.array([1,2,3,4,5,6], dtype='int32')
b = np.array([7,8,9,1,3,4], dtype='int32')

In [ ]:
print('The mean for the a: ',a.mean())
print('The mean for the b: ',b.mean())

The mean for the a:  3.5
The mean for the b:  5.333333333333333


In [ ]:
a.min()

1

In [ ]:
a.max()

6

In [ ]:
np.arange(1,8,3)

array([1, 4, 7])

In [ ]:
np.zeros((4,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [ ]:
np.ones((3,6))

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [ ]:
np.full((3,2), 'a')

array([['a', 'a'],
       ['a', 'a'],
       ['a', 'a']], dtype='<U1')

In [ ]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [ ]:
np.random.random((2,3))

array([[0.22336216, 0.37410119, 0.42653558],
       [0.1871641 , 0.71134207, 0.82734459]])

In [ ]:
a = np.array([[1,2],[3,4],[5,6]])
bool_idx = (a>2)
bool_idx

array([[False, False],
       [ True,  True],
       [ True,  True]])

In [ ]:
b= np.array([372, 4,4,5])
print(b[b>99])

[372]


In [ ]:
a = np.array([[1,2,3],[4,5,6]], dtype='int32')
b = np.array([[7,8,9],[1,3,4]], dtype='int32')

In [ ]:
print(a+b)
print(np.add(a,b))

[[ 8 10 12]
 [ 5  8 10]]
[[ 8 10 12]
 [ 5  8 10]]


In [ ]:
print(a-b)
print(np.subtract(a,b))

[[-6 -6 -6]
 [ 3  2  2]]
[[-6 -6 -6]
 [ 3  2  2]]


In [ ]:
print(a*b)
print(np.multiply(a,b))

[[ 7 16 27]
 [ 4 15 24]]
[[ 7 16 27]
 [ 4 15 24]]


In [ ]:
print(a/b)
print(np.divide(a,b))

[[0.14285714 0.25       0.33333333]
 [4.         1.66666667 1.5       ]]
[[0.14285714 0.25       0.33333333]
 [4.         1.66666667 1.5       ]]


In [ ]:
print("Sqaure root for a is:\n",np.sqrt(a),'\n')
print("Sqaure root for b is:\n",np.sqrt(b))

Sqaure root for a is:
 [[1.         1.41421356 1.73205081]
 [2.         2.23606798 2.44948974]] 

Sqaure root for b is:
 [[2.64575131 2.82842712 3.        ]
 [1.         1.73205081 2.        ]]


In [ ]:
x = np.array([1,2,3,4,5,6], dtype='int32')
y = np.array([7,8,9,1,3,4], dtype='int32')

In [ ]:
print(x@y)
print(np.dot(x,y))
print(x.dot(y))

93
93
93


In [ ]:
print(a)
print("Transpose\n",a.T)

[[1 2 3]
 [4 5 6]]
Transpose
 [[1 4]
 [2 5]
 [3 6]]


In [ ]:
np.random.randint(1,7,(4,5))

array([[5, 4, 6, 6, 6],
       [3, 5, 1, 2, 5],
       [5, 5, 3, 4, 2],
       [3, 3, 3, 6, 1]])

In [ ]:
np.random.randn()

1.215683345345114

In [ ]:
s1 = '1$'
s2 = 'batch'

x = np.char.add(s2,s1)
print(x)

batch1$
